name: Ambiente Desenvolvimento

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    name: Compilação
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configurar o JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn -B compile --file pom.xml
      
  code-quality:
      name: Qualidade de Código
      needs: build
      runs-on: ubuntu-latest
      
      steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Adiciona permissão para mvnw
        run: chmod +x mvnw
      - name: Análise SonarCloud
        run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-devops-project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEM }}
          
  sec-tests:
     name: Análise de Segurança
     needs: build
     runs-on: ubuntu-letest
     
     steps:
     - name: Simula execução de testes de segurança
       run: echo
     
        
